var hierarchy =
[
    [ "APER_CFG_T", "structAPER__CFG__T.html", null ],
    [ "APER_T", "structAPER__T.html", null ],
    [ "ARG_S", "structARG__S.html", null ],
    [ "ARG_T", "structARG__T.html", null ],
    [ "ARGOPT_T", "structARGOPT__T.html", null ],
    [ "Array< T, Dev >", "classArray.html", null ],
    [ "Array< Array >", "classArray.html", null ],
    [ "Array< Array< Comp, Gpu >, Cpu >", "classArray.html", [
      [ "Cell< Comp, Gpu >", "classCell.html", null ]
    ] ],
    [ "Array< Array< culoc_t > >", "classArray.html", null ],
    [ "Array< Array< int, Gpu >, Cpu >", "classArray.html", [
      [ "Cell< int, Gpu >", "classCell.html", null ]
    ] ],
    [ "Array< Array< Real, Gpu >, Cpu >", "classArray.html", [
      [ "Cell< Real, Gpu >", "classCell.html", null ]
    ] ],
    [ "Array< Array< Real, Pinned > >", "classArray.html", null ],
    [ "Array< Array< short2, Gpu >, Cpu >", "classArray.html", [
      [ "Cell< short2, Gpu >", "classCell.html", null ]
    ] ],
    [ "Array< Array< T, Cpu >, Cpu >", "classArray.html", [
      [ "Cell< T, Dev >", "classCell.html", null ]
    ] ],
    [ "Array< atm_prep_t >", "classArray.html", null ],
    [ "Array< ATYPE, Gpu >", "classArray.html", null ],
    [ "Array< Comp *, Gpu >", "classArray.html", null ],
    [ "Array< Comp *, Pinned >", "classArray.html", null ],
    [ "Array< Comp, Gpu >", "classArray.html", null ],
    [ "Array< cuda_recon::LAP_T, Gpu >", "classArray.html", null ],
    [ "Array< cudtf_t >", "classArray.html", null ],
    [ "Array< cufftHandle >", "classArray.html", null ],
    [ "Array< cugrid_t >", "classArray.html", null ],
    [ "Array< cuimat >", "classArray.html", null ],
    [ "Array< culoc_t >", "classArray.html", null ],
    [ "Array< cumap_t >", "classArray.html", null ],
    [ "Array< cupowfs_t >", "classArray.html", null ],
    [ "Array< curccell >", "classArray.html", null ],
    [ "Array< cusp >", "classArray.html", null ],
    [ "Array< cuwfs_t >", "classArray.html", null ],
    [ "Array< GPU_FDPCG_T, Gpu >", "classArray.html", null ],
    [ "Array< GPU_GP_T, Gpu >", "classArray.html", null ],
    [ "Array< GTYPE, Gpu >", "classArray.html", null ],
    [ "Array< int *, Gpu >", "classArray.html", null ],
    [ "Array< int *, Pinned >", "classArray.html", null ],
    [ "Array< int >", "classArray.html", null ],
    [ "Array< int, Gpu >", "classArray.html", null ],
    [ "Array< map2map >", "classArray.html", null ],
    [ "Array< Real *, Gpu >", "classArray.html", null ],
    [ "Array< Real *, Pinned >", "classArray.html", null ],
    [ "Array< Real >", "classArray.html", null ],
    [ "Array< Real, Gpu >", "classArray.html", null ],
    [ "Array< Real, Pinned >", "classArray.html", null ],
    [ "Array< short2 *, Gpu >", "classArray.html", null ],
    [ "Array< short2 *, Pinned >", "classArray.html", null ],
    [ "Array< short2, Gpu >", "classArray.html", null ],
    [ "Array< stream_t >", "classArray.html", null ],
    [ "Array< T *, Gpu >", "classArray.html", null ],
    [ "Array< T *, Pinned >", "classArray.html", null ],
    [ "Array< T, Cpu >", "classArray.html", null ],
    [ "ASTER_S", "structASTER__S.html", null ],
    [ "ATM_CFG_T", "structATM__CFG__T.html", null ],
    [ "atm_prep_t", "structatm__prep__t.html", null ],
    [ "ATMR_CFG_T", "structATMR__CFG__T.html", null ],
    [ "ccccell", "structccccell.html", null ],
    [ "cccell", "structcccell.html", null ],
    [ "ccell", "structccell.html", null ],
    [ "cell", "structcell.html", null ],
    [ "cuda_recon::CGTMP_T", "classcuda__recon_1_1CGTMP__T.html", null ],
    [ "cmat", "structcmat.html", null ],
    [ "CN2EST_CFG_T", "structCN2EST__CFG__T.html", null ],
    [ "cn2est_t", "structcn2est__t.html", null ],
    [ "CN2PAIR_T", "structCN2PAIR__T.html", null ],
    [ "Cpu< T >", "classCpu.html", [
      [ "Pinned< T >", "classPinned.html", null ]
    ] ],
    [ "csp", "structcsp.html", null ],
    [ "cspcell", "structcspcell.html", null ],
    [ "cudata_t", "classcudata__t.html", null ],
    [ "cudtf_t", "structcudtf__t.html", null ],
    [ "cuda_wfs::cufieldstop_t", "classcuda__wfs_1_1cufieldstop__t.html", null ],
    [ "cuglobal_t", "classcuglobal__t.html", null ],
    [ "cugrid_t", "classcugrid__t.html", [
      [ "cumap_t", "classcumap__t.html", null ]
    ] ],
    [ "cuda_wfs::cullt_t", "classcuda__wfs_1_1cullt__t.html", null ],
    [ "cullt_t", "structcullt__t.html", null ],
    [ "culoc_t", "classculoc__t.html", [
      [ "cupts_t", "classcupts__t.html", null ]
    ] ],
    [ "cuperf_g", "classcuperf__g.html", null ],
    [ "cuperf_t", "classcuperf__t.html", null ],
    [ "cupowfs_t", "structcupowfs__t.html", null ],
    [ "cuda_wfs::curand_t", "classcuda__wfs_1_1curand__t.html", null ],
    [ "cuda_recon::cusolve_cgpre", "classcuda__recon_1_1cusolve__cgpre.html", [
      [ "cuda_recon::cufdpcg_t", "classcuda__recon_1_1cufdpcg__t.html", null ]
    ] ],
    [ "cuda_recon::cusolve_l", "classcuda__recon_1_1cusolve__l.html", [
      [ "cuda_recon::cusolve_cbs", "classcuda__recon_1_1cusolve__cbs.html", null ],
      [ "cuda_recon::cusolve_cg", "classcuda__recon_1_1cusolve__cg.html", [
        [ "cuda_recon::cufit_grid", "classcuda__recon_1_1cufit__grid.html", null ],
        [ "cuda_recon::cumoao_t", "classcuda__recon_1_1cumoao__t.html", null ],
        [ "cuda_recon::cusolve_sparse", "classcuda__recon_1_1cusolve__sparse.html", null ],
        [ "cuda_recon::cutomo_grid", "classcuda__recon_1_1cutomo__grid.html", null ]
      ] ],
      [ "cuda_recon::cusolve_mvm", "classcuda__recon_1_1cusolve__mvm.html", null ]
    ] ],
    [ "cuda_recon::cusolve_r", "classcuda__recon_1_1cusolve__r.html", [
      [ "cuda_recon::cufit_grid", "classcuda__recon_1_1cufit__grid.html", null ],
      [ "cuda_recon::cusolve_sparse", "classcuda__recon_1_1cusolve__sparse.html", null ],
      [ "cuda_recon::cutomo_grid", "classcuda__recon_1_1cutomo__grid.html", null ]
    ] ],
    [ "cusp", "classcusp.html", null ],
    [ "cuda_wfs::cuwfs_base", "classcuda__wfs_1_1cuwfs__base.html", [
      [ "cuda_wfs::cupywfs_t", "classcuda__wfs_1_1cupywfs__t.html", null ],
      [ "cuda_wfs::cushwfs_t", "classcuda__wfs_1_1cushwfs__t.html", [
        [ "cuda_wfs::cushgeom_t", "classcuda__wfs_1_1cushgeom__t.html", [
          [ "cuda_wfs::cushg_t", "classcuda__wfs_1_1cushg__t.html", null ],
          [ "cuda_wfs::cushz_t", "classcuda__wfs_1_1cushz__t.html", null ]
        ] ],
        [ "cuda_wfs::cushphy_t", "classcuda__wfs_1_1cushphy__t.html", null ]
      ] ]
    ] ],
    [ "cuda_wfs::cuwfs_info", "classcuda__wfs_1_1cuwfs__info.html", null ],
    [ "cuwfs_t", "classcuwfs__t.html", null ],
    [ "cuda_wfs::cuwfs_t", "classcuda__wfs_1_1cuwfs__t.html", null ],
    [ "DBG_CFG_T", "structDBG__CFG__T.html", null ],
    [ "dcccell", "structdcccell.html", null ],
    [ "dccell", "structdccell.html", null ],
    [ "dcell", "structdcell.html", null ],
    [ "dir_t", "structdir__t.html", null ],
    [ "dither_t", "classdither__t.html", null ],
    [ "DITHER_T", "structDITHER__T.html", null ],
    [ "DM_CFG_T", "structDM__CFG__T.html", null ],
    [ "dmat", "structdmat.html", null ],
    [ "dsp", "structdsp.html", null ],
    [ "dspcell", "structdspcell.html", null ],
    [ "DTF_S", "structDTF__S.html", null ],
    [ "DTF_T", "structDTF__T.html", null ],
    [ "ETF_T", "structETF__T.html", null ],
    [ "event_t", "structevent__t.html", null ],
    [ "EVL_CFG_T", "structEVL__CFG__T.html", null ],
    [ "FDPCG_T", "structFDPCG__T.html", null ],
    [ "FIT_CFG_T", "structFIT__CFG__T.html", null ],
    [ "FIT_T", "structFIT__T.html", null ],
    [ "FRACTAL_T", "structFRACTAL__T.html", null ],
    [ "GENATM_T", "structGENATM__T.html", null ],
    [ "GLOBAL_T", "structGLOBAL__T.html", null ],
    [ "Gpu< T >", "classGpu.html", null ],
    [ "GPU_CFG_T", "structGPU__CFG__T.html", null ],
    [ "GPU_FDPCG_T", "structGPU__FDPCG__T.html", null ],
    [ "GPU_GP_T", "structGPU__GP__T.html", null ],
    [ "header_t", "structheader__t.html", null ],
    [ "icccell", "structicccell.html", null ],
    [ "iccell", "structiccell.html", null ],
    [ "imat", "structimat.html", null ],
    [ "INTSTAT_T", "structINTSTAT__T.html", null ],
    [ "INVPSD_T", "structINVPSD__T.html", null ],
    [ "kalman_t", "structkalman__t.html", null ],
    [ "cuda_recon::LAP_T", "structcuda__recon_1_1LAP__T.html", null ],
    [ "lcell", "structlcell.html", null ],
    [ "LLT_CFG_T", "structLLT__CFG__T.html", null ],
    [ "LLT_T", "structLLT__T.html", null ],
    [ "lmat", "structlmat.html", null ],
    [ "LOAD_CFG_T", "structLOAD__CFG__T.html", null ],
    [ "loc_t", "structloc__t.html", null ],
    [ "locccell", "structlocccell.html", null ],
    [ "loccell", "structloccell.html", null ],
    [ "locfft_t", "structlocfft__t.html", null ],
    [ "lock_t", "classlock__t.html", null ],
    [ "locstat_t", "structlocstat__t.html", null ],
    [ "locstatcol_t", "structlocstatcol__t.html", null ],
    [ "LSR_CFG_T", "structLSR__CFG__T.html", null ],
    [ "Magic< T >", "structMagic.html", null ],
    [ "Magic< double >", "structMagic_3_01double_01_4.html", null ],
    [ "Magic< double2 >", "structMagic_3_01double2_01_4.html", null ],
    [ "Magic< float >", "structMagic_3_01float_01_4.html", null ],
    [ "Magic< float2 >", "structMagic_3_01float2_01_4.html", null ],
    [ "Magic< int >", "structMagic_3_01int_01_4.html", null ],
    [ "Magic< long int >", "structMagic_3_01long_01int_01_4.html", null ],
    [ "MAOS_S", "structMAOS__S.html", null ],
    [ "map2map_shared_t", "structmap2map__shared__t.html", null ],
    [ "map2map_t", "structmap2map__t.html", null ],
    [ "map_t", "structmap__t.html", null ],
    [ "mapccell", "structmapccell.html", null ],
    [ "mapcell", "structmapcell.html", null ],
    [ "MISREG_CFG_T", "structMISREG__CFG__T.html", null ],
    [ "MOAO_CFG_T", "structMOAO__CFG__T.html", null ],
    [ "MOAO_T", "structMOAO__T.html", null ],
    [ "mt_state", "structmt__state.html", null ],
    [ "MUV_T", "structMUV__T.html", null ],
    [ "NGSMOD_T", "structNGSMOD__T.html", null ],
    [ "nonCopyable", "classnonCopyable.html", [
      [ "cuda_recon::cufdpcg_t", "classcuda__recon_1_1cufdpcg__t.html", null ],
      [ "cuda_recon::curecon_geom", "classcuda__recon_1_1curecon__geom.html", null ],
      [ "cuda_recon::curecon_t", "classcuda__recon_1_1curecon__t.html", null ],
      [ "cuda_recon::cusolve_cbs", "classcuda__recon_1_1cusolve__cbs.html", null ],
      [ "cuda_recon::cusolve_cg", "classcuda__recon_1_1cusolve__cg.html", null ],
      [ "cuda_recon::cusolve_muv", "classcuda__recon_1_1cusolve__muv.html", null ],
      [ "cuda_recon::cusolve_mvm", "classcuda__recon_1_1cusolve__mvm.html", null ],
      [ "map2map", "classmap2map.html", null ]
    ] ],
    [ "PARMS_S", "structPARMS__S.html", null ],
    [ "PARMS_T", "structPARMS__T.html", null ],
    [ "PISTAT_S", "structPISTAT__S.html", null ],
    [ "PLOT_CFG_T", "structPLOT__CFG__T.html", null ],
    [ "POWFS_CFG_T", "structPOWFS__CFG__T.html", null ],
    [ "POWFS_S", "structPOWFS__S.html", null ],
    [ "POWFS_T", "structPOWFS__T.html", null ],
    [ "PROPDATA_T", "structPROPDATA__T.html", null ],
    [ "pts_t", "structpts__t.html", null ],
    [ "PYWFS_T", "structPYWFS__T.html", null ],
    [ "RECON_CFG_T", "structRECON__CFG__T.html", null ],
    [ "RECON_T", "structRECON__T.html", null ],
    [ "RefP< T, Dev >", "classRefP.html", null ],
    [ "rmap_t", "structrmap__t.html", null ],
    [ "rmapccell", "structrmapccell.html", null ],
    [ "rmapcell", "structrmapcell.html", null ],
    [ "SAVE_CFG_T", "structSAVE__CFG__T.html", null ],
    [ "scccell", "structscccell.html", null ],
    [ "sccell", "structsccell.html", null ],
    [ "scell", "structscell.html", null ],
    [ "SERVO_T", "structSERVO__T.html", null ],
    [ "SHO_T", "structSHO__T.html", null ],
    [ "SIM_CFG_T", "structSIM__CFG__T.html", null ],
    [ "SIM_S", "structSIM__S.html", null ],
    [ "SIM_SAVE_T", "structSIM__SAVE__T.html", null ],
    [ "SIM_T", "structSIM__T.html", null ],
    [ "SKYC_S", "structSKYC__S.html", null ],
    [ "smat", "structsmat.html", null ],
    [ "spchol", "structspchol.html", null ],
    [ "ssp", "structssp.html", null ],
    [ "sspcell", "structsspcell.html", null ],
    [ "STAR_S", "structSTAR__S.html", null ],
    [ "STATUS_T", "structSTATUS__T.html", null ],
    [ "stream_t", "classstream__t.html", null ],
    [ "thread_t", "structthread__t.html", null ],
    [ "TOMO_CFG_T", "structTOMO__CFG__T.html", null ],
    [ "cuda_recon::W01_T", "classcuda__recon_1_1W01__T.html", null ],
    [ "WFS_CFG_T", "structWFS__CFG__T.html", null ],
    [ "WFS_S", "structWFS__S.html", null ],
    [ "WFSINTS_T", "structWFSINTS__T.html", null ],
    [ "ZB_S", "structZB__S.html", null ],
    [ "zcccell", "structzcccell.html", null ],
    [ "zccell", "structzccell.html", null ],
    [ "zcell", "structzcell.html", null ],
    [ "zmat", "structzmat.html", null ],
    [ "zsp", "structzsp.html", null ],
    [ "zspcell", "structzspcell.html", null ],
    [ "long", "classlong.html", null ]
];