var hierarchy =
[
    [ "APER_CFG_T", "structAPER__CFG__T.html", null ],
    [ "APER_T", "structAPER__T.html", null ],
    [ "ARG_S", "structARG__S.html", null ],
    [ "ARG_T", "structARG__T.html", null ],
    [ "ARGOPT_T", "structARGOPT__T.html", null ],
    [ "Array< T >", "classArray.html", null ],
    [ "Array< Array >", "classArray.html", null ],
    [ "Array< Array< culoc_t > >", "classArray.html", null ],
    [ "Array< cuda_recon::map_ray >", "classArray.html", null ],
    [ "Array< cudtf_t >", "classArray.html", null ],
    [ "Array< cufftHandle >", "classArray.html", null ],
    [ "Array< cugrid_t >", "classArray.html", null ],
    [ "Array< culoc_t >", "classArray.html", null ],
    [ "Array< cumap_t >", "classArray.html", null ],
    [ "Array< cupowfs_t >", "classArray.html", null ],
    [ "Array< curccell >", "classArray.html", null ],
    [ "Array< cusp >", "classArray.html", null ],
    [ "Array< cuwfs_t >", "classArray.html", null ],
    [ "Array< int >", "classArray.html", null ],
    [ "Array< Real >", "classArray.html", null ],
    [ "Array< stream_t >", "classArray.html", null ],
    [ "ASTER_S", "structASTER__S.html", null ],
    [ "ATM_CFG_T", "structATM__CFG__T.html", null ],
    [ "atm_prep_t", "structatm__prep__t.html", null ],
    [ "ATMR_CFG_T", "structATMR__CFG__T.html", null ],
    [ "ccccell", "structccccell.html", null ],
    [ "cccell", "structcccell.html", null ],
    [ "ccell", "structccell.html", null ],
    [ "cell", "structcell.html", null ],
    [ "CGTMP_T", "structCGTMP__T.html", null ],
    [ "cmat", "structcmat.html", null ],
    [ "CN2EST_CFG_T", "structCN2EST__CFG__T.html", null ],
    [ "cn2est_t", "structcn2est__t.html", null ],
    [ "CN2PAIR_T", "structCN2PAIR__T.html", null ],
    [ "csp", "structcsp.html", null ],
    [ "cspcell", "structcspcell.html", null ],
    [ "cucell< T >", "classcucell.html", null ],
    [ "cucell< Comp >", "classcucell.html", null ],
    [ "cucell< int >", "classcucell.html", null ],
    [ "cucell< Real >", "classcucell.html", null ],
    [ "cucell< short2 >", "classcucell.html", null ],
    [ "cuda_recon::cucgpre_t", "classcuda__recon_1_1cucgpre__t.html", [
      [ "cuda_recon::cufdpcg_t", "classcuda__recon_1_1cufdpcg__t.html", null ]
    ] ],
    [ "cudata_t", "structcudata__t.html", null ],
    [ "cudtf_t", "structcudtf__t.html", null ],
    [ "cuda_wfs::cufieldstop_t", "classcuda__wfs_1_1cufieldstop__t.html", null ],
    [ "cugrid_t", "classcugrid__t.html", [
      [ "cumap_t", "classcumap__t.html", null ]
    ] ],
    [ "cuda_wfs::cullt_t", "classcuda__wfs_1_1cullt__t.html", null ],
    [ "cullt_t", "structcullt__t.html", null ],
    [ "culoc_t", "classculoc__t.html", [
      [ "cupts_t", "classcupts__t.html", null ]
    ] ],
    [ "cumat< T >", "classcumat.html", null ],
    [ "cumat< Comp >", "classcumat.html", null ],
    [ "cumat< cuda_recon::LAP_T >", "classcumat.html", null ],
    [ "cumat< GPU_FDPCG_T >", "classcumat.html", null ],
    [ "cumat< GPU_GP_T >", "classcumat.html", null ],
    [ "cumat< int >", "classcumat.html", null ],
    [ "cumat< Real >", "classcumat.html", null ],
    [ "cumat< short >", "classcumat.html", null ],
    [ "cumat< short2 >", "classcumat.html", null ],
    [ "cuperf_t", "structcuperf__t.html", null ],
    [ "cupowfs_t", "structcupowfs__t.html", null ],
    [ "cuda_wfs::curand_t", "classcuda__wfs_1_1curand__t.html", null ],
    [ "cuda_recon::cusolve_l", "classcuda__recon_1_1cusolve__l.html", [
      [ "cuda_recon::cucg_t", "classcuda__recon_1_1cucg__t.html", [
        [ "cuda_recon::cufit_grid", "classcuda__recon_1_1cufit__grid.html", null ],
        [ "cuda_recon::cumoao_t", "classcuda__recon_1_1cumoao__t.html", null ],
        [ "cuda_recon::cusolve_sparse", "classcuda__recon_1_1cusolve__sparse.html", null ],
        [ "cuda_recon::cutomo_grid", "classcuda__recon_1_1cutomo__grid.html", null ]
      ] ],
      [ "cuda_recon::cusolve_cbs", "classcuda__recon_1_1cusolve__cbs.html", null ],
      [ "cuda_recon::cusolve_mvm", "classcuda__recon_1_1cusolve__mvm.html", null ]
    ] ],
    [ "cuda_recon::cusolve_r", "classcuda__recon_1_1cusolve__r.html", [
      [ "cuda_recon::cufit_grid", "classcuda__recon_1_1cufit__grid.html", null ],
      [ "cuda_recon::cusolve_sparse", "classcuda__recon_1_1cusolve__sparse.html", null ],
      [ "cuda_recon::cutomo_grid", "classcuda__recon_1_1cutomo__grid.html", null ]
    ] ],
    [ "cusp", "classcusp.html", null ],
    [ "cuda_wfs::cuwfs_base", "classcuda__wfs_1_1cuwfs__base.html", [
      [ "cuda_wfs::cupywfs_t", "classcuda__wfs_1_1cupywfs__t.html", null ],
      [ "cuda_wfs::cushwfs_t", "classcuda__wfs_1_1cushwfs__t.html", [
        [ "cuda_wfs::cushgeom_t", "classcuda__wfs_1_1cushgeom__t.html", [
          [ "cuda_wfs::cushg_t", "classcuda__wfs_1_1cushg__t.html", null ],
          [ "cuda_wfs::cushz_t", "classcuda__wfs_1_1cushz__t.html", null ]
        ] ],
        [ "cuda_wfs::cushphy_t", "classcuda__wfs_1_1cushphy__t.html", null ]
      ] ]
    ] ],
    [ "cuda_wfs::cuwfs_info", "classcuda__wfs_1_1cuwfs__info.html", null ],
    [ "cuda_wfs::cuwfs_t", "classcuda__wfs_1_1cuwfs__t.html", null ],
    [ "cuwfs_t", "classcuwfs__t.html", null ],
    [ "DBG_CFG_T", "structDBG__CFG__T.html", null ],
    [ "dcccell", "structdcccell.html", null ],
    [ "dccell", "structdccell.html", null ],
    [ "dcell", "structdcell.html", null ],
    [ "cuda_recon::dir_t", "structcuda__recon_1_1dir__t.html", null ],
    [ "DITHER_T", "structDITHER__T.html", null ],
    [ "dither_t", "classdither__t.html", null ],
    [ "DM_CFG_T", "structDM__CFG__T.html", null ],
    [ "dmat", "structdmat.html", null ],
    [ "dsp", "structdsp.html", null ],
    [ "dspcell", "structdspcell.html", null ],
    [ "DTF_S", "structDTF__S.html", null ],
    [ "DTF_T", "structDTF__T.html", null ],
    [ "ETF_T", "structETF__T.html", null ],
    [ "event_t", "structevent__t.html", null ],
    [ "EVL_CFG_T", "structEVL__CFG__T.html", null ],
    [ "FDPCG_T", "structFDPCG__T.html", null ],
    [ "FIT_CFG_T", "structFIT__CFG__T.html", null ],
    [ "FIT_T", "structFIT__T.html", null ],
    [ "FRACTAL_T", "structFRACTAL__T.html", null ],
    [ "GENATM_T", "structGENATM__T.html", null ],
    [ "GLOBAL_T", "structGLOBAL__T.html", null ],
    [ "GPU_CFG_T", "structGPU__CFG__T.html", null ],
    [ "GPU_DATA_T", "structGPU__DATA__T.html", null ],
    [ "GPU_FDPCG_T", "structGPU__FDPCG__T.html", null ],
    [ "GPU_GP_T", "structGPU__GP__T.html", null ],
    [ "gpu_map2map_shared_t", "structgpu__map2map__shared__t.html", null ],
    [ "header_t", "structheader__t.html", null ],
    [ "icccell", "structicccell.html", null ],
    [ "iccell", "structiccell.html", null ],
    [ "INTSTAT_T", "structINTSTAT__T.html", null ],
    [ "INVPSD_T", "structINVPSD__T.html", null ],
    [ "kalman_t", "structkalman__t.html", null ],
    [ "cuda_recon::LAP_T", "structcuda__recon_1_1LAP__T.html", null ],
    [ "lcell", "structlcell.html", null ],
    [ "LLT_CFG_T", "structLLT__CFG__T.html", null ],
    [ "LLT_T", "structLLT__T.html", null ],
    [ "lmat", "structlmat.html", null ],
    [ "LOAD_CFG_T", "structLOAD__CFG__T.html", null ],
    [ "loc_t", "structloc__t.html", null ],
    [ "locccell", "structlocccell.html", null ],
    [ "loccell", "structloccell.html", null ],
    [ "locfft_t", "structlocfft__t.html", null ],
    [ "lock_t", "classlock__t.html", null ],
    [ "locstat_t", "structlocstat__t.html", null ],
    [ "locstatcol_t", "structlocstatcol__t.html", null ],
    [ "LSR_CFG_T", "structLSR__CFG__T.html", null ],
    [ "MAOS_S", "structMAOS__S.html", null ],
    [ "map_t", "structmap__t.html", null ],
    [ "mapccell", "structmapccell.html", null ],
    [ "mapcell", "structmapcell.html", null ],
    [ "MISREG_CFG_T", "structMISREG__CFG__T.html", null ],
    [ "MOAO_CFG_T", "structMOAO__CFG__T.html", null ],
    [ "MOAO_T", "structMOAO__T.html", null ],
    [ "mt_state", "structmt__state.html", null ],
    [ "MUV_T", "structMUV__T.html", null ],
    [ "MVM_IGPU_T", "structMVM__IGPU__T.html", null ],
    [ "mvm_t", "structmvm__t.html", null ],
    [ "NGSMOD_T", "structNGSMOD__T.html", null ],
    [ "nonCopyable", "classnonCopyable.html", [
      [ "cuda_recon::cucg_t", "classcuda__recon_1_1cucg__t.html", null ],
      [ "cuda_recon::cufdpcg_t", "classcuda__recon_1_1cufdpcg__t.html", null ],
      [ "cuda_recon::cumuv_t", "classcuda__recon_1_1cumuv__t.html", null ],
      [ "cuda_recon::curecon_geom", "classcuda__recon_1_1curecon__geom.html", null ],
      [ "cuda_recon::curecon_t", "classcuda__recon_1_1curecon__t.html", null ],
      [ "cuda_recon::cusolve_cbs", "classcuda__recon_1_1cusolve__cbs.html", null ],
      [ "cuda_recon::cusolve_mvm", "classcuda__recon_1_1cusolve__mvm.html", null ],
      [ "cuda_recon::map_ray", "classcuda__recon_1_1map__ray.html", null ]
    ] ],
    [ "PARMS_S", "structPARMS__S.html", null ],
    [ "PARMS_T", "structPARMS__T.html", null ],
    [ "PISTAT_S", "structPISTAT__S.html", null ],
    [ "PLOT_CFG_T", "structPLOT__CFG__T.html", null ],
    [ "POWFS_CFG_T", "structPOWFS__CFG__T.html", null ],
    [ "POWFS_S", "structPOWFS__S.html", null ],
    [ "POWFS_T", "structPOWFS__T.html", null ],
    [ "PROP_WRAP_T", "structPROP__WRAP__T.html", null ],
    [ "PROPDATA_T", "structPROPDATA__T.html", null ],
    [ "pts_t", "structpts__t.html", null ],
    [ "PYWFS_T", "structPYWFS__T.html", null ],
    [ "RECON_CFG_T", "structRECON__CFG__T.html", null ],
    [ "RECON_T", "structRECON__T.html", null ],
    [ "rmap_t", "structrmap__t.html", null ],
    [ "rmapccell", "structrmapccell.html", null ],
    [ "rmapcell", "structrmapcell.html", null ],
    [ "SAVE_CFG_T", "structSAVE__CFG__T.html", null ],
    [ "scccell", "structscccell.html", null ],
    [ "sccell", "structsccell.html", null ],
    [ "scell", "structscell.html", null ],
    [ "SERVO_T", "structSERVO__T.html", null ],
    [ "SHO_T", "structSHO__T.html", null ],
    [ "SIM_CFG_T", "structSIM__CFG__T.html", null ],
    [ "SIM_S", "structSIM__S.html", null ],
    [ "SIM_SAVE_T", "structSIM__SAVE__T.html", null ],
    [ "SIM_T", "structSIM__T.html", null ],
    [ "SKYC_S", "structSKYC__S.html", null ],
    [ "smat", "structsmat.html", null ],
    [ "spchol", "structspchol.html", null ],
    [ "ssp", "structssp.html", null ],
    [ "sspcell", "structsspcell.html", null ],
    [ "STAR_S", "structSTAR__S.html", null ],
    [ "STATUS_T", "structSTATUS__T.html", null ],
    [ "stream_t", "structstream__t.html", null ],
    [ "task_t", "structtask__t.html", null ],
    [ "thread_t", "structthread__t.html", null ],
    [ "TOMO_CFG_T", "structTOMO__CFG__T.html", null ],
    [ "cuda_recon::W01_T", "classcuda__recon_1_1W01__T.html", null ],
    [ "WFS_CFG_T", "structWFS__CFG__T.html", null ],
    [ "WFS_S", "structWFS__S.html", null ],
    [ "cuda_wfs::wfscfg_t", "structcuda__wfs_1_1wfscfg__t.html", null ],
    [ "WFSINTS_T", "structWFSINTS__T.html", null ],
    [ "ZB_S", "structZB__S.html", null ],
    [ "zcccell", "structzcccell.html", null ],
    [ "zccell", "structzccell.html", null ],
    [ "zcell", "structzcell.html", null ],
    [ "zmat", "structzmat.html", null ],
    [ "zsp", "structzsp.html", null ],
    [ "zspcell", "structzspcell.html", null ]
];