var hierarchy =
[
    [ "aper_cfg_t", "d4/d38/parms_8h.html#da/dfc/structaper__cfg__t", null ],
    [ "aper_t", "d6/d94/maos_2types_8h.html#d5/deb/structaper__t", null ],
    [ "arg_t", "d4/d38/parms_8h.html#d1/d81/structarg__t", null ],
    [ "argopt_t", "d4/d08/misc_8h.html#d5/d5e/structargopt__t", null ],
    [ "atm_cfg_t", "d4/d38/parms_8h.html#d0/d0d/structatm__cfg__t", null ],
    [ "atm_prep_t", "da/dc6/structatm__prep__t.html", null ],
    [ "atmr_cfg_t", "d4/d38/parms_8h.html#d9/da3/structatmr__cfg__t", null ],
    [ "ccccell", "df/def/type_8h.html#d5/dec/structccccell", null ],
    [ "cccell", "df/def/type_8h.html#d6/de5/structcccell", null ],
    [ "ccell", "df/def/type_8h.html#d8/d42/structccell", null ],
    [ "cell", "df/def/type_8h.html#db/d76/structcell", null ],
    [ "cgtmp_t", "d1/dad/classcgtmp__t.html", null ],
    [ "cmat", "db/d16/structcmat.html", null ],
    [ "cn2est_cfg_t", "d4/d38/parms_8h.html#d9/df1/structcn2est__cfg__t", null ],
    [ "cn2est_pair_t", "dc/d59/cn2est_8h.html#d2/d4d/structcn2est__pair__t", null ],
    [ "cn2est_t", "dc/d59/cn2est_8h.html#d8/d2f/structcn2est__t", null ],
    [ "Cpu< T >", "dd/d45/class_cpu.html", [
      [ "Pinned< Real * >", "df/db5/class_pinned.html", null ],
      [ "Pinned< T * >", "df/db5/class_pinned.html", null ],
      [ "Pinned< Real >", "df/db5/class_pinned.html", null ],
      [ "Pinned< Comp * >", "df/db5/class_pinned.html", null ],
      [ "Pinned< int * >", "df/db5/class_pinned.html", null ],
      [ "Pinned< short2 * >", "df/db5/class_pinned.html", null ],
      [ "Pinned< T >", "df/db5/class_pinned.html", null ]
    ] ],
    [ "Cpu< Array< culoc_t > >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< Array< Real, Pinned > >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< atm_prep_t >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< CellArray >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< Comp * >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< cudtf_t >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< cufftHandle >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< cuimat >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< culoc_t >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< cupowfs_t >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< cuwfs_t >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< int * >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< int >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< map2map >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< Real * >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< Real >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< short2 * >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< stream_t >", "dd/d45/class_cpu.html", null ],
    [ "Cpu< T * >", "dd/d45/class_cpu.html", null ],
    [ "CpuObj< T >", "d3/dd7/class_cpu_obj.html", null ],
    [ "CpuObj< cugrid_t >", "d3/dd7/class_cpu_obj.html", null ],
    [ "CpuObj< cumap_t >", "d3/dd7/class_cpu_obj.html", null ],
    [ "CpuObj< curccell >", "d3/dd7/class_cpu_obj.html", null ],
    [ "CpuObj< cusp >", "d3/dd7/class_cpu_obj.html", null ],
    [ "CpuObj< NumArray< Comp, Gpu > >", "d3/dd7/class_cpu_obj.html", null ],
    [ "CpuObj< NumArray< int, Gpu > >", "d3/dd7/class_cpu_obj.html", null ],
    [ "CpuObj< NumArray< Real, Gpu > >", "d3/dd7/class_cpu_obj.html", null ],
    [ "CpuObj< NumArray< short2, Gpu > >", "d3/dd7/class_cpu_obj.html", null ],
    [ "CpuObj< NumArray< T, Cpu > >", "d3/dd7/class_cpu_obj.html", null ],
    [ "csp", "df/def/type_8h.html#d1/d2a/structcsp", null ],
    [ "cspcell", "df/def/type_8h.html#d8/d70/structcspcell", null ],
    [ "cudata_t", "db/d5f/classcudata__t.html", null ],
    [ "cudtf_t", "df/d33/structcudtf__t.html", null ],
    [ "cuetf_t", "da/df1/structcuetf__t.html", null ],
    [ "cuda_wfs::cufieldstop_t", "d5/daf/classcuda__wfs_1_1cufieldstop__t.html", null ],
    [ "cuglobal_t", "d7/de7/classcuglobal__t.html", null ],
    [ "cugrid_t", "d5/d0d/classcugrid__t.html", [
      [ "cumap_t", "dc/d87/classcumap__t.html", null ]
    ] ],
    [ "cuda_wfs::cullt_t", "d7/d7e/classcuda__wfs_1_1cullt__t.html", null ],
    [ "cullt_t", "dd/dd3/structcullt__t.html", null ],
    [ "culoc_t", "df/d28/classculoc__t.html", [
      [ "cupts_t", "dc/d1e/classcupts__t.html", null ]
    ] ],
    [ "cumemcache_t", "de/d37/classcumemcache__t.html", null ],
    [ "cuperf_g", "d2/dbe/classcuperf__g.html", null ],
    [ "cuperf_t", "d3/d66/classcuperf__t.html", null ],
    [ "cupowfs_t", "db/d46/structcupowfs__t.html", null ],
    [ "cuda_wfs::curand_t", "d9/db9/classcuda__wfs_1_1curand__t.html", null ],
    [ "cusolve_cgpre", "d6/d87/classcusolve__cgpre.html", [
      [ "cufdpcg_t", "d5/db0/classcufdpcg__t.html", null ]
    ] ],
    [ "cusolve_l", "d3/d82/classcusolve__l.html", [
      [ "cusolve_cbs", "d4/d35/classcusolve__cbs.html", null ],
      [ "cusolve_cg", "de/d5d/classcusolve__cg.html", [
        [ "cufit_grid", "d2/dc2/classcufit__grid.html", null ],
        [ "cumoao_t", "d4/d1a/classcumoao__t.html", null ],
        [ "cusolve_sparse", "d2/d23/classcusolve__sparse.html", null ],
        [ "cutomo_grid", "db/d1f/classcutomo__grid.html", null ]
      ] ],
      [ "cusolve_mvm", "de/dda/classcusolve__mvm.html", null ]
    ] ],
    [ "cusolve_r", "df/d37/classcusolve__r.html", [
      [ "cufit_grid", "d2/dc2/classcufit__grid.html", null ],
      [ "cusolve_sparse", "d2/d23/classcusolve__sparse.html", null ],
      [ "cutomo_grid", "db/d1f/classcutomo__grid.html", null ]
    ] ],
    [ "cusp", "d4/d25/classcusp.html", null ],
    [ "cusp_ref", "df/d03/structcusp__ref.html", null ],
    [ "cuda_wfs::cuwfs_base", "d3/d61/classcuda__wfs_1_1cuwfs__base.html", [
      [ "cuda_wfs::cupywfs_t", "dc/d6b/classcuda__wfs_1_1cupywfs__t.html", null ],
      [ "cuda_wfs::cushwfs_t", "da/d4f/classcuda__wfs_1_1cushwfs__t.html", [
        [ "cuda_wfs::cushgeom_t", "d3/dee/classcuda__wfs_1_1cushgeom__t.html", [
          [ "cuda_wfs::cushg_t", "d5/d5c/classcuda__wfs_1_1cushg__t.html", null ],
          [ "cuda_wfs::cushz_t", "df/d79/classcuda__wfs_1_1cushz__t.html", null ]
        ] ],
        [ "cuda_wfs::cushphy_t", "d2/de3/classcuda__wfs_1_1cushphy__t.html", null ]
      ] ]
    ] ],
    [ "cuda_wfs::cuwfs_info", "da/dc0/classcuda__wfs_1_1cuwfs__info.html", null ],
    [ "cuda_wfs::cuwfs_t", "d0/dec/classcuda__wfs_1_1cuwfs__t.html", null ],
    [ "cuwfs_t", "dc/d85/classcuwfs__t.html", null ],
    [ "dbg_cfg_t", "d4/d38/parms_8h.html#d6/dbf/structdbg__cfg__t", null ],
    [ "dcccell", "df/def/type_8h.html#d6/d2e/structdcccell", null ],
    [ "dccell", "df/def/type_8h.html#d1/df9/structdccell", null ],
    [ "dcell", "df/def/type_8h.html#df/d47/structdcell", null ],
    [ "dir_t", "d3/db8/structdir__t.html", null ],
    [ "dist_cfg_t", "d4/d38/parms_8h.html#d5/d06/structdist__cfg__t", null ],
    [ "dither_cfg_t", "d4/d38/parms_8h.html#d0/dea/structdither__cfg__t", null ],
    [ "Dither_t", "d1/db1/class_dither__t.html", null ],
    [ "dither_t", "d6/d94/maos_2types_8h.html#d3/def/structdither__t", null ],
    [ "dlist", "d6/d93/structdlist.html", null ],
    [ "dm_cfg_t", "d4/d38/parms_8h.html#d9/df5/structdm__cfg__t", null ],
    [ "dmat", "d3/d27/structdmat.html", null ],
    [ "dsp", "df/def/type_8h.html#de/d35/structdsp", null ],
    [ "dspcell", "df/def/type_8h.html#d6/ddb/structdspcell", null ],
    [ "dtf_t", "d6/d89/mkdtf_8h.html#d3/d9b/structdtf__t", null ],
    [ "dtype< T >", "d6/de0/classdtype.html", null ],
    [ "etf_t", "d6/d89/mkdtf_8h.html#d4/d5b/structetf__t", null ],
    [ "event_t", "da/d67/structevent__t.html", null ],
    [ "evl_cfg_t", "d4/d38/parms_8h.html#d3/d46/structevl__cfg__t", null ],
    [ "fdpcg_t", "d6/d94/maos_2types_8h.html#df/d53/structfdpcg__t", null ],
    [ "fit_cfg_t", "d4/d38/parms_8h.html#d7/d76/structfit__cfg__t", null ],
    [ "fit_t", "d6/d94/maos_2types_8h.html#da/d3f/structfit__t", null ],
    [ "fractal_t", "d6/d94/maos_2types_8h.html#d2/d15/structfractal__t", null ],
    [ "genatm_t", "d2/d75/turbulence_8h.html#d0/d92/structgenatm__t", null ],
    [ "global_t", "d6/d94/maos_2types_8h.html#db/d00/structglobal__t", null ],
    [ "Gpu< T >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< AReal >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< Comp * >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< Comp >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< gpu_fdpcg_t >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< gpu_gp_t >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< GReal >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< int * >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< int >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< lap_t >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< Real * >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< Real >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< short2 * >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< short2 >", "d0/ddc/class_gpu.html", null ],
    [ "Gpu< T * >", "d0/ddc/class_gpu.html", null ],
    [ "gpu_cfg_t", "d4/d38/parms_8h.html#de/d64/structgpu__cfg__t", null ],
    [ "gpu_fdpcg_t", "d9/dc3/structgpu__fdpcg__t.html", null ],
    [ "gpu_gp_t", "dd/dd4/structgpu__gp__t.html", null ],
    [ "header_t", "d3/d7f/bin_8h.html#de/d7e/structheader__t", null ],
    [ "header_t.__unnamed39__", "d3/d7f/bin_8h.html#d2/dcc/unionheader__t_8____unnamed39____", null ],
    [ "imat", "d6/d6f/structimat.html", null ],
    [ "intstat_t", "d6/d94/maos_2types_8h.html#de/d79/structintstat__t", null ],
    [ "invpsd_t", "d6/d94/maos_2types_8h.html#d7/dff/structinvpsd__t", null ],
    [ "kalman_t", "df/d07/kalman_8h.html#d4/d41/structkalman__t", null ],
    [ "lap_t", "d8/dcd/structlap__t.html", null ],
    [ "lcccell", "df/def/type_8h.html#df/d5e/structlcccell", null ],
    [ "lccell", "df/def/type_8h.html#d2/d09/structlccell", null ],
    [ "lcell", "df/def/type_8h.html#db/d4d/structlcell", null ],
    [ "listen_opt_t", "d0/dcc/structlisten__opt__t.html", null ],
    [ "llt_cfg_t", "d4/d38/parms_8h.html#d1/dde/structllt__cfg__t", null ],
    [ "llt_t", "d6/d94/maos_2types_8h.html#de/df6/structllt__t", null ],
    [ "lmat", "d7/da0/structlmat.html", null ],
    [ "load_cfg_t", "d4/d38/parms_8h.html#d3/d1e/structload__cfg__t", null ],
    [ "loc_t", "df/def/type_8h.html#da/ddc/structloc__t", null ],
    [ "loc_t.__unnamed23__", "df/def/type_8h.html#d1/d54/unionloc__t_8____unnamed23____", null ],
    [ "loc_t.__unnamed23__.__unnamed27__", "df/def/type_8h.html#d4/d9c/structloc__t_8____unnamed23_____8____unnamed27____", null ],
    [ "loc_t.__unnamed25__", "df/def/type_8h.html#df/dbf/structloc__t_8____unnamed25____", null ],
    [ "locccell", "df/def/type_8h.html#d3/d30/structlocccell", null ],
    [ "loccell", "df/def/type_8h.html#dc/da1/structloccell", null ],
    [ "locfft_t", "db/d1f/locfft_8h.html#d3/dcd/structlocfft__t", null ],
    [ "lock_t", "d7/dc3/classlock__t.html", null ],
    [ "locstat_t", "df/def/type_8h.html#db/d43/structlocstat__t", null ],
    [ "locstatcol_t", "df/def/type_8h.html#db/d5f/structlocstatcol__t", null ],
    [ "lsr_cfg_t", "d4/d38/parms_8h.html#db/dea/structlsr__cfg__t", null ],
    [ "Magic< T >", "d2/d6e/struct_magic.html", null ],
    [ "Magic< double >", "db/daa/struct_magic_3_01double_01_4.html", null ],
    [ "Magic< double2 >", "da/dcf/struct_magic_3_01double2_01_4.html", null ],
    [ "Magic< float >", "d1/d9c/struct_magic_3_01float_01_4.html", null ],
    [ "Magic< float2 >", "dd/d61/struct_magic_3_01float2_01_4.html", null ],
    [ "Magic< int >", "d3/dea/struct_magic_3_01int_01_4.html", null ],
    [ "Magic< long int >", "d5/df1/struct_magic_3_01long_01int_01_4.html", null ],
    [ "map2map_shared_t", "db/dcd/structmap2map__shared__t.html", null ],
    [ "map2map_t", "db/db2/structmap2map__t.html", null ],
    [ "map_t", "df/def/type_8h.html#d6/da3/structmap__t", null ],
    [ "map_t.__unnamed15__", "df/def/type_8h.html#df/d4b/unionmap__t_8____unnamed15____", null ],
    [ "map_t.__unnamed15__.__unnamed17__", "d4/d37/structmap__t_8____unnamed15_____8____unnamed17____.html", null ],
    [ "mapccell", "df/def/type_8h.html#d7/d25/structmapccell", null ],
    [ "mapcell", "df/def/type_8h.html#d2/d8c/structmapcell", null ],
    [ "moao_cfg_t", "d4/d38/parms_8h.html#d1/d0a/structmoao__cfg__t", null ],
    [ "moao_t", "d6/d94/maos_2types_8h.html#d5/d68/structmoao__t", null ],
    [ "mt_state", "dc/d95/structmt__state.html", null ],
    [ "muv_t", "d3/dc7/muv_8h.html#dd/d34/structmuv__t", null ],
    [ "mvm_igpu_t", "d8/d36/mvm__trans_8cu.html#d8/dd6/structmvm__igpu__t", null ],
    [ "ncpa_cfg_t", "d4/d38/parms_8h.html#d5/d84/structncpa__cfg__t", null ],
    [ "ngsmod_t", "d6/d94/maos_2types_8h.html#d2/df8/structngsmod__t", null ],
    [ "nonCopyable", "dc/d27/classnon_copyable.html", [
      [ "cufdpcg_t", "d5/db0/classcufdpcg__t.html", null ],
      [ "curecon_geom", "dd/dae/classcurecon__geom.html", null ],
      [ "curecon_t", "d5/d6a/classcurecon__t.html", null ],
      [ "cusolve_cbs", "d4/d35/classcusolve__cbs.html", null ],
      [ "cusolve_cg", "de/d5d/classcusolve__cg.html", null ],
      [ "cusolve_muv", "d0/db6/classcusolve__muv.html", null ],
      [ "cusolve_mvm", "de/dda/classcusolve__mvm.html", null ],
      [ "map2map", "d6/db6/classmap2map.html", null ]
    ] ],
    [ "parms_t", "d4/d38/parms_8h.html#d4/d51/structparms__t", null ],
    [ "plot_cfg_t", "d4/d38/parms_8h.html#de/d7c/structplot__cfg__t", null ],
    [ "plot_opts", "de/d28/draw_8h.html#d3/de8/structplot__opts", null ],
    [ "plot_opts.__unnamed8__", "de/d28/draw_8h.html#dd/d34/unionplot__opts_8____unnamed8____", null ],
    [ "powfs_cfg_t", "d4/d38/parms_8h.html#d5/d33/structpowfs__cfg__t", null ],
    [ "powfs_t", "d6/d94/maos_2types_8h.html#da/dcf/structpowfs__t", null ],
    [ "propdata_t", "d3/d84/lib_2accphi_8h.html#d9/db3/structpropdata__t", null ],
    [ "pts_t", "df/def/type_8h.html#de/d88/structpts__t", null ],
    [ "pts_t.__unnamed29__", "df/def/type_8h.html#d9/df8/unionpts__t_8____unnamed29____", null ],
    [ "pts_t.__unnamed29__.__unnamed31__", "df/def/type_8h.html#db/d8b/structpts__t_8____unnamed29_____8____unnamed31____", null ],
    [ "pts_t.__unnamed29__.__unnamed31__.__unnamed33__", "df/def/type_8h.html#db/da7/unionpts__t_8____unnamed29_____8____unnamed31_____8____unnamed33____", null ],
    [ "pts_t.__unnamed29__.__unnamed31__.__unnamed33__.__unnamed37__", "df/def/type_8h.html#d4/ddb/structpts__t_8____unnamed29_____8____unnamed31_____8____unnamed33_____8____unnamed37____", null ],
    [ "pts_t.__unnamed29__.__unnamed31__.__unnamed35__", "df/def/type_8h.html#d0/da8/unionpts__t_8____unnamed29_____8____unnamed31_____8____unnamed35____", null ],
    [ "pywfs_cfg_t", "d9/d19/pywfs_8h.html#d0/d1d/structpywfs__cfg__t", null ],
    [ "pywfs_t", "d9/d19/pywfs_8h.html#d2/d8c/structpywfs__t", null ],
    [ "recon_cfg_t", "d4/d38/parms_8h.html#d1/d32/structrecon__cfg__t", null ],
    [ "recon_t", "d6/d94/maos_2types_8h.html#d1/d27/structrecon__t", null ],
    [ "RefP< T, Dev >", "dd/db6/class_ref_p.html", [
      [ "Array< T, CpuObj >", "d5/d21/class_array.html", [
        [ "CellArray< T >", "d1/d12/class_cell_array.html", [
          [ "NumCell< Real, Gpu >", "d4/d0f/class_num_cell.html", null ],
          [ "NumCell< Comp, Gpu >", "d4/d0f/class_num_cell.html", null ],
          [ "NumCell< int, Gpu >", "d4/d0f/class_num_cell.html", null ],
          [ "NumCell< short2, Gpu >", "d4/d0f/class_num_cell.html", null ],
          [ "NumCell< T, Dev >", "d4/d0f/class_num_cell.html", null ]
        ] ]
      ] ],
      [ "Array< T, Cpu >", "d5/d21/class_array.html", null ],
      [ "Array< NumArray< T, Cpu >, CpuObj >", "d5/d21/class_array.html", null ],
      [ "Array< NumArray< Real, Gpu >, CpuObj >", "d5/d21/class_array.html", null ],
      [ "Array< Real, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< Real *, Pinned >", "d5/d21/class_array.html", null ],
      [ "Array< Real *, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< T *, Pinned >", "d5/d21/class_array.html", null ],
      [ "Array< T *, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< Real, Cpu >", "d5/d21/class_array.html", null ],
      [ "Array< Real, Pinned >", "d5/d21/class_array.html", null ],
      [ "Array< int >", "d5/d21/class_array.html", null ],
      [ "Array< cumap_t, CpuObj >", "d5/d21/class_array.html", null ],
      [ "Array< cupowfs_t >", "d5/d21/class_array.html", null ],
      [ "Array< CellArray >", "d5/d21/class_array.html", null ],
      [ "Array< AReal, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< GReal, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< Comp, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< int, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< NumArray< Comp, Gpu >, CpuObj >", "d5/d21/class_array.html", null ],
      [ "Array< Comp *, Pinned >", "d5/d21/class_array.html", null ],
      [ "Array< Comp *, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< cufftHandle >", "d5/d21/class_array.html", null ],
      [ "Array< gpu_fdpcg_t, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< cugrid_t, CpuObj >", "d5/d21/class_array.html", null ],
      [ "Array< cuwfs_t >", "d5/d21/class_array.html", null ],
      [ "Array< atm_prep_t >", "d5/d21/class_array.html", null ],
      [ "Array< map2map >", "d5/d21/class_array.html", null ],
      [ "Array< Real >", "d5/d21/class_array.html", null ],
      [ "Array< Array< Real, Pinned > >", "d5/d21/class_array.html", null ],
      [ "Array< Array< culoc_t > >", "d5/d21/class_array.html", null ],
      [ "Array< culoc_t >", "d5/d21/class_array.html", null ],
      [ "Array< cuimat >", "d5/d21/class_array.html", null ],
      [ "Array< NumArray< int, Gpu >, CpuObj >", "d5/d21/class_array.html", null ],
      [ "Array< int *, Pinned >", "d5/d21/class_array.html", null ],
      [ "Array< int *, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< curccell, CpuObj >", "d5/d21/class_array.html", null ],
      [ "Array< NumArray< short2, Gpu >, CpuObj >", "d5/d21/class_array.html", null ],
      [ "Array< short2, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< short2 *, Pinned >", "d5/d21/class_array.html", null ],
      [ "Array< short2 *, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< cusp, CpuObj >", "d5/d21/class_array.html", null ],
      [ "Array< gpu_gp_t, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< lap_t, Gpu >", "d5/d21/class_array.html", null ],
      [ "Array< stream_t >", "d5/d21/class_array.html", null ],
      [ "Array< cudtf_t >", "d5/d21/class_array.html", null ],
      [ "Array< T, Dev >", "d5/d21/class_array.html", [
        [ "CellArray< NumArray< T, Cpu > >", "d1/d12/class_cell_array.html", null ],
        [ "CellArray< NumArray< Real, Gpu > >", "d1/d12/class_cell_array.html", null ],
        [ "CellArray< cumap_t >", "d1/d12/class_cell_array.html", null ],
        [ "CellArray< NumArray< Comp, Gpu > >", "d1/d12/class_cell_array.html", null ],
        [ "CellArray< cugrid_t >", "d1/d12/class_cell_array.html", null ],
        [ "CellArray< NumArray< int, Gpu > >", "d1/d12/class_cell_array.html", null ],
        [ "CellArray< curccell >", "d1/d12/class_cell_array.html", null ],
        [ "CellArray< NumArray< short2, Gpu > >", "d1/d12/class_cell_array.html", null ],
        [ "CellArray< cusp >", "d1/d12/class_cell_array.html", null ],
        [ "NumArray< T, Cpu >", "d0/d44/class_num_array.html", null ],
        [ "NumArray< Real, Gpu >", "d0/d44/class_num_array.html", null ],
        [ "NumArray< Real >", "d0/d44/class_num_array.html", null ],
        [ "NumArray< Real, Pinned >", "d0/d44/class_num_array.html", null ],
        [ "NumArray< AReal, Gpu >", "d0/d44/class_num_array.html", null ],
        [ "NumArray< GReal, Gpu >", "d0/d44/class_num_array.html", null ],
        [ "NumArray< Comp, Gpu >", "d0/d44/class_num_array.html", null ],
        [ "NumArray< int, Gpu >", "d0/d44/class_num_array.html", null ],
        [ "NumArray< short2, Gpu >", "d0/d44/class_num_array.html", null ],
        [ "NumArray< T, Dev >", "d0/d44/class_num_array.html", null ]
      ] ]
    ] ],
    [ "RefP< AReal, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< Array< culoc_t >, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< Array< Real, Pinned >, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< atm_prep_t, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< CellArray, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< Comp *, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< Comp *, Pinned >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< Comp, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< cudtf_t, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< cufftHandle, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< cugrid_t, CpuObj >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< cuimat, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< culoc_t, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< cumap_t, CpuObj >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< cupowfs_t, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< curccell, CpuObj >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< cusp, CpuObj >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< cuwfs_t, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< gpu_fdpcg_t, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< gpu_gp_t, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< GReal, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< int *, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< int *, Pinned >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< int, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< int, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< lap_t, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< map2map, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< NumArray< Comp, Gpu >, CpuObj >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< NumArray< int, Gpu >, CpuObj >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< NumArray< Real, Gpu >, CpuObj >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< NumArray< short2, Gpu >, CpuObj >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< NumArray< T, Cpu >, CpuObj >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< Real *, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< Real *, Pinned >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< Real, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< Real, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< Real, Pinned >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< short2 *, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< short2 *, Pinned >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< short2, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< stream_t, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< T *, Gpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< T *, Pinned >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< T, Cpu >", "dd/db6/class_ref_p.html", null ],
    [ "RefP< T, CpuObj >", "dd/db6/class_ref_p.html", null ],
    [ "rmap_t", "df/def/type_8h.html#d3/d27/structrmap__t", null ],
    [ "rmap_t.__unnamed19__", "df/def/type_8h.html#d2/d1a/unionrmap__t_8____unnamed19____", null ],
    [ "rmap_t.__unnamed19__.__unnamed21__", "d4/d68/structrmap__t_8____unnamed19_____8____unnamed21____.html", null ],
    [ "rmapccell", "df/def/type_8h.html#d3/d5f/structrmapccell", null ],
    [ "rmapcell", "df/def/type_8h.html#de/db0/structrmapcell", null ],
    [ "save_cfg_t", "d4/d38/parms_8h.html#de/ddb/structsave__cfg__t", null ],
    [ "scccell", "df/def/type_8h.html#d0/d27/structscccell", null ],
    [ "sccell", "df/def/type_8h.html#db/d40/structsccell", null ],
    [ "scell", "df/def/type_8h.html#d0/d54/structscell", null ],
    [ "servo_t", "de/d09/servo_8h.html#da/d58/structservo__t", null ],
    [ "servo_t.__unnamed10__", "de/d09/servo_8h.html#df/d14/unionservo__t_8____unnamed10____", null ],
    [ "servo_t.__unnamed12__", "de/d09/servo_8h.html#d7/dbc/unionservo__t_8____unnamed12____", null ],
    [ "sho_t", "de/d09/servo_8h.html#d7/d37/structsho__t", null ],
    [ "sim_cfg_t", "d4/d38/parms_8h.html#d3/d8f/structsim__cfg__t", null ],
    [ "sim_save_t", "d6/d94/maos_2types_8h.html#d1/d15/structsim__save__t", null ],
    [ "sim_t", "d6/d94/maos_2types_8h.html#d1/da4/structsim__t", null ],
    [ "smat", "d4/d6c/structsmat.html", null ],
    [ "spchol", "db/da8/chol_8h.html#d8/d3f/structspchol", null ],
    [ "ssp", "df/def/type_8h.html#dc/d44/structssp", null ],
    [ "sspcell", "df/def/type_8h.html#d0/db5/structsspcell", null ],
    [ "status_t", "d4/d64/scheduler__client_8h.html#d6/d3a/structstatus__t", null ],
    [ "stream_t", "dc/de6/classstream__t.html", null ],
    [ "task_t", "d6/daa/structtask__t.html", null ],
    [ "thread_t", "db/dd5/thread_8h.html#d4/dd6/structthread__t", null ],
    [ "tomo_cfg_t", "d4/d38/parms_8h.html#d1/d86/structtomo__cfg__t", null ],
    [ "tp_counter_t", "d3/dec/thread__pool_8h.html#d2/d26/structtp__counter__t", null ],
    [ "udp_t", "db/d54/sockio_8h.html#d4/d74/structudp__t", null ],
    [ "w01_t", "d0/d2e/classw01__t.html", null ],
    [ "wfs_cfg_t", "d4/d38/parms_8h.html#d2/d57/structwfs__cfg__t", null ],
    [ "cuda_wfs::wfscfg_t", "d1/d27/structcuda__wfs_1_1wfscfg__t.html", null ],
    [ "wfsflags_t", "d6/d94/maos_2types_8h.html#de/d27/structwfsflags__t", null ],
    [ "wfsints_t", "d6/d94/maos_2types_8h.html#db/dc4/structwfsints__t", null ],
    [ "wfsr_cfg_t", "d4/d38/parms_8h.html#d6/d65/structwfsr__cfg__t", null ],
    [ "zcccell", "df/def/type_8h.html#d5/dcd/structzcccell", null ],
    [ "zccell", "df/def/type_8h.html#d1/d27/structzccell", null ],
    [ "zcell", "df/def/type_8h.html#d0/d43/structzcell", null ],
    [ "zmat", "d9/d5c/structzmat.html", null ],
    [ "zsp", "df/def/type_8h.html#d4/d71/structzsp", null ],
    [ "zspcell", "df/def/type_8h.html#d9/d87/structzspcell", null ],
    [ "Comp", "da/d77/class_comp.html", null ],
    [ "Comp *", "db/dbe/class_comp_01_5.html", null ],
    [ "Comp *", "db/dbe/class_comp_01_5.html", null ],
    [ "Comp * *", "dd/d08/class_comp_01_5_01_5.html", null ],
    [ "CpuObj< T > *", "d8/dc9/class_cpu_obj_3_01_t_01_4_01_5.html", null ],
    [ "cuimat", "dc/d0d/classcuimat.html", null ],
    [ "cuimat *", "d1/d1f/classcuimat_01_5.html", null ],
    [ "long", "d7/d63/classlong.html", null ],
    [ "Real", "d0/d58/class_real.html", null ],
    [ "Real *", "d3/d4b/class_real_01_5.html", null ],
    [ "Real * *", "dc/de0/class_real_01_5_01_5.html", null ],
    [ "short2", "d6/d70/classshort2.html", null ],
    [ "short2 *", "dc/d4d/classshort2_01_5.html", null ],
    [ "unsigned int *", "d2/d74/classunsigned_01int_01_5.html", null ]
];