#50 percentile Ground Layer
#75 percentile Free Atmosphere 

# Best-guess at L0
atm.L0       = 30    #atm outer scale (m)

# R0 zenith (m) calculated by maos_utils function Fried() from MASS/DIMM
atm.r0z      = 0.143


# Turbulence screen heights above telescope (m)
# atm.ht, atm.wt, atm.ws, atm.wsdeg must have the same length
atm.ws       = [5.6  5.77 6.25 7.57 7.0  7.0  7.0 7.0 7.0 6.5 12.8 22  9.5 5.6]
atm.ht       = [0 15 30 45 120 200 280 360 440 807 4349 8000 12000 19501]
atm.wt       = [0.291 0.148 0.039 0.002 0.020 0.010 0.008 0.005 0.001 0.112 0.150 0.097 0.078 0.038]
