#Define Strata with KASM (GLAO or LTAO)

#Simulation parameters
include     = sim.conf
#Define Keck pupil
include     = keck.conf

sim.end     = 6020  #10 seconds
sim.dt      = 1/600
sim.htel    = 4145 #Updated 2026-07-31 (also in latest keck.conf)

#AO type.
include     = dm_single.conf
dm.dx       = [0.1624] #this is the average spacing of actuators within the clear aperture. Updated 2026-07-31
dm.ht       = [-128.7] #conjugation Updated 2026-07-31 based on https://www2.keck.hawaii.edu/optics/teldocs/prescriptions.html

#Atmospheric profile
include     = atm_mk50pGL_50pFA.conf #Mauna Kea 13N 50%.  Updated 2026-07-31
atm.size    = [128 128] #to covert the largest FoV.
sim.wspsd   = PSD_Keck_ws20mas_vib26mas_rad2.fits
#Including configurations for reconstruction (tomo/fitting)
include     = recon.conf

#Additional parameters debugging purpose (no need to change)
include     = dbg.conf

#Wavefront sensor information
include      = wfs_lgs_ttf.conf #LGS + TTF WFS
wfs.thetax   = [-1 -1 1 1 1]*0.355 #WFS location on sky. To be scaled by powfs.astscale
wfs.thetay   = [-1 1 -1 1 0]*0.355
powfs0_llt.ox= [-1 -1 1 1]*6.5 #LGS LLT position at M1 coordinate
powfs0_llt.oy= [-1 1 -1 1]*1
powfs.nwfs   = [4 1] #4 LGS, 1 TTF WFS
powfs.dsa    = [0 -2] #subaperture size. 0 matches ground DM.
powfs.mag    = [7.5 8.5] #magnitude at zenith.
powfs.dtrat  = [1 1] 
powfs.nwvl   = [1 1] #number of wavelength for each powfs
powfs.wvl    = [0.589e-6 0.7e-6] #wavelength
powfs.wvlwts = [1 1] #wavelength weights. 
powfs.pixtheta=[1 0.5] #pixel scale in arc seconds
powfs.pixpsa= [10 6] #number of pixels per subaperture (1d)
powfs.rne   = [0.5 0.5] #read out noise

#Evaluation and fitting FoV information.
include     = fit_cir60.conf
fit.wt      = [0.5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] 
fit.fov     = 180 #DM Fitting Fov diameter in arcseconds

#Performance Evaluation
include     = evl_x.conf #Along a radius
evl.fov     = 180 #Evaluation oV diameter in arcseconds
evl.wvl	    = [0.31 0.5 0.7 0.8 0.9 1.0 1.25 1.65 2.15]*1e-6 #For IR add 1.25 1.65 2.15
evl.psfsize	= [768, 512, 256, 192, 192, 192, 128, 96, 64] #For IR add 128, 96, 64
evl.psfmean = 1 #save time averaged PSF 
evl.psfol   = 1 #save open loop PSF
evl.psf     = [1] #enable PSF for direction
evl.psfisim = 20 #frame to start computing PSF
#Other paramters
#recon.glao  = 1 #Uncomment to use GLAO algorithm instead of Tomography
#powfs.step=[0 1200] #Uncomment to disable NGS WFS.
#powfs.phystep=[-1] #Uncomment to use geometric WFS