#Define Strata with KASM (GLAO or LTAO)

#Simulation parameters
include     = sim.conf
sim.end     = 1200 
sim.dt      = 1/600

#Define Keck pupil
include     = keck.conf

#AO type.
include     = dm_single.conf
dm.dx       = [0.185] #use a square pattern with 0.185m pitch on M1 for now
dm.ht       = [-80] #conjugation

#Atmospheric profile
include     = atm_mk50pGL_50pFA.conf #Mauna Kea 13N 50%.

#Including configurations for reconstruction (tomo/fitting)
include     = recon.conf

#Additional parameters debugging purpose (no need to change)
include     = dbg.conf

#Wavefront sensor information
include      = wfs_lgs_ttf.conf #LGS + TTF WFS
wfs.thetax   = [-1 -1 1 1 1]/2 #WFS location on sky. To be scaled by powfs.astscale
wfs.thetay   = [-1 1 -1 1 0]/2
powfs0_llt.ox= [-1 -1 1 1]*6.5 #LGS LLT position at M1 coordinate
powfs0_llt.oy= [-1 1 -1 1]*1
powfs.nwfs   = [4 1] #4 LGS, 1 TTF WFS
powfs.dsa    = [0.185 -2] #subaperture size
powfs.mag    = [7.5 10] #magnitude
powfs.dtrat  = [1 1] 
powfs.nwvl   = [1 1] #number of wavelength for each powfs
powfs.wvl    = [0.589e-6 0.7e-6] #wavelength
powfs.wvlwts = [1 1] #wavelength weights. 
powfs.pixtheta=[1 0.5] #pixel scale in arc seconds
powfs.pixpsa= [6 6] #number of pixels per subaperture (1d)
powfs.rne   = [3 1] #read out noise

#Evaluation and fitting FoV information.
include     = fit_cir60.conf
fit.wt      = [0.5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] 
fit.fov     = 180 #DM Fitting Fov diameter in arcseconds

#Performance Evaluation
include     = evl_x.conf #Along a radius
evl.fov     = 180 #Evaluation oV diameter in arcseconds
evl.wvl	    = [0.31 0.5 0.7 0.8 0.9 1.0 1.25 1.65 2.15]*1e-6 #For IR add 1.25 1.65 2.15
evl.psfsize	= [768, 512, 256, 192, 192, 192, 128, 96, 64] #For IR add 128, 96, 64
evl.psfmean = 1 #save time averaged PSF 
evl.psfol   = 1 #save open loop PSF
evl.psf     = [1] #enable PSF for direction
evl.psfisim = 20 #frame to start computing PSF
#Other paramters
#recon.glao  = 1 #Uncomment to use GLAO algorithm instead of Tomography
#powfs.step=[0 1200] #Uncomment to disable NGS WFS.
#powfs.phystep=[-1] #Uncomment to use geometric WFS