aper.d     	  = [30 3.6] #outer (d) and inner diameter (din) in meter. may contain one number for [d] or two numbers for [d din]. din=0 when omitted. [0] to use size from aper.fnamp
aper.fnamp    = "TMT_23cm6.bin" #The telescope aperture amplitude map file. It contains a nx*ny 2d array of values between 0 and 1 with the following keywords:
	              # dx, dy: grid spacing in m.
				  # ox oy: grid origin in m. FFT style origin (-nx/2*dx) is used if omitted.
				  # ht. height in m. always at 0.
                  