name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout maos
      uses: actions/checkout@v2
      with:
        path: maos
    - name: autogen
      run: cd maos && ./autogen.sh
    - name: configure
      run: mkdir build && cd build && ../maos/configure --enable-release --enable-doxygen
    - name: make
      run: |
        cd build 
        make 
        PATH+=":$HOME/bin"
        make doc
    - name: checkout gh-pages 
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: doc
    - name: update doc and commit
      run: | 
        cd  doc
        rm -rf *
        cp -a ../build/doxygen-doc/html/* .
        git config user.name Lianqi Wang
        git config user.email lianqiw@gmail.com
        git add .
        git commit -m "Automatically updated" && git push || echo "no need to update doc"
    - name: make check
      run: cd build && make check
    - name: make distcheck
      run: cd build && make distcheck
    - uses: actions/upload-artifact@v2
      with:
        name: maos-bin
        path: build/bin/
    
